/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FarmZone } from "./FarmZone";
import { FarmZoneCountArgs } from "./FarmZoneCountArgs";
import { FarmZoneFindManyArgs } from "./FarmZoneFindManyArgs";
import { FarmZoneFindUniqueArgs } from "./FarmZoneFindUniqueArgs";
import { DeleteFarmZoneArgs } from "./DeleteFarmZoneArgs";
import { FarmZoneService } from "../farmZone.service";
@graphql.Resolver(() => FarmZone)
export class FarmZoneResolverBase {
  constructor(protected readonly service: FarmZoneService) {}

  async _farmZonesMeta(
    @graphql.Args() args: FarmZoneCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FarmZone])
  async farmZones(
    @graphql.Args() args: FarmZoneFindManyArgs
  ): Promise<FarmZone[]> {
    return this.service.farmZones(args);
  }

  @graphql.Query(() => FarmZone, { nullable: true })
  async farmZone(
    @graphql.Args() args: FarmZoneFindUniqueArgs
  ): Promise<FarmZone | null> {
    const result = await this.service.farmZone(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FarmZone)
  async deleteFarmZone(
    @graphql.Args() args: DeleteFarmZoneArgs
  ): Promise<FarmZone | null> {
    try {
      return await this.service.deleteFarmZone(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
